export const tags = [
  'Account Exec',
  'Account Mgr',
  'Admin',
  'Analyst',
  'Art Dir',
  'Back-end Dev',
  'Biz Dev Mgr',
  'Brand Mgr',
  'CEO',
  'CFO',
  'CMO',
  'COO',
  'CTO',
  'Client Mgr',
  'Comm Mgr',
  'Content Cr',
  'Content Ed',
  'Content Mgr',
  'Creative Dir',
  'CSM',
  'CX Mgr',
  'Data Eng',
  'Data Sci',
  'DB Admin',
  'Designer',
  'DevOps Eng',
  'Digital Mkt Mgr',
  'Digital Spclst',
  'E-com Mgr',
  'Events Coord',
  'Events Mgr',
  'Front-end Dev',
  'Full Stack Dev',
  'Graphic Des',
  'Growth Mkt',
  'HR Coord',
  'HR Mgr',
  'IT Mgr',
  'IT Support',
  'Mkt Analyst',
  'Mkt Asst',
  'Mkt Coord',
  'Mkt Dir',
  'Mkt Mgr',
  'Mobile Dev',
  'Net Admin',
  'Ops Mgr',
  'Prod Des',
  'Prod Mgr',
  'Prog Mgr',
  'Proj Coord',
  'Proj Mgr',
  'PR Mgr',
  'QA Eng',
  'Recruiter',
  'Sales Assoc',
  'Sales Dir',
  'Sales Mgr',
  'Sales Rep',
  'SEO Mgr',
  'SEO Spclst',
  'SM Mgr',
  'Software Dev',
  'Software Eng',
  'Sol Arch',
  'Support Eng',
  'Sys Admin',
  'Tech Lead',
  'Tech Support',
  'Tech Writer',
  'UI/UX Des',
  'UX Res',
  'Video Prod',
  'Visual Des',
  'Web Des',
  'Web Dev'
]
